# 📊 Analisis Data dengan Pandas

Pandas adalah pustaka Python untuk manipulasi dan analisis data. Notebook ini mencakup:

1. **Series & DataFrame** — struktur data pandas
2. **Membaca Data** — dari CSV, Excel, dan sumber lainnya
3. **Eksplorasi Data** — melihat, merangkum, dan memahami data
4. **Seleksi & Filtering** — memilih baris/kolom tertentu

> 💡 **Jalankan setiap sel** dengan memilihnya dan tekan `Shift + Enter`.

---
## 0️⃣ Setup & Import

Pastikan pandas sudah terinstall. Jika belum: `pip install pandas`

In [48]:
# ── Import pustaka ──
import pandas as pd
import numpy as np

print(f"Pandas version : {pd.__version__}")
print(f"NumPy version  : {np.__version__}")

Pandas version : 3.0.6
NumPy version  : 2.5.3

---
## 1️⃣ Series & DataFrame

Dua struktur data utama di pandas:
- **Series** — satu dimensi (seperti list/array dengan label)
- **DataFrame** — dua dimensi (seperti tabel/spreadsheet)

In [49]:
# ── Series ──
# Series mirip list tapi memiliki index label

nilai = pd.Series([85, 92, 78, 90, 88])
print("Series sederhana:")
print(nilai)
print()

# Series dengan index kustom
nilai_label = pd.Series(
    [85, 92, 78, 90, 88],
    index=["Budi", "Rina", "Charlie", "Dewi", "Eko"]
)
print("Series dengan index:")
print(nilai_label)
print()

# Akses elemen
print(f"Nilai Budi : {nilai_label['Budi']}")
print(f"Nilai Rina : {nilai_label['Rina']}")

Series sederhana:
0    85
1    92
2    78
3    90
4    88
dtype: int64

Series dengan index:
Budi       85
Rina       92
Charlie    78
Dewi       90
Eko        88
dtype: int64

Nilai Budi : 85
Nilai Rina : 92

In [50]:
# ── DataFrame dari dictionary ──
# Cara paling umum: dictionary dengan key = kolom

data_mahasiswa = {
    "nama"   : ["Budi", "Rina", "Charlie", "Dewi", "Eko"],
    "jurusan": ["Teknik Mesin", "Teknik Elektro", "Teknik Sipil",
                 "Teknik Mesin", "Teknik Elektro"],
    "nilai"  : [85, 92, 78, 90, 88],
    "semester": [4, 6, 4, 6, 4],
}

df = pd.DataFrame(data_mahasiswa)
print("DataFrame Mahasiswa:")
df

DataFrame Mahasiswa:

      nama         jurusan  nilai  semester
0     Budi    Teknik Mesin     85         4
1     Rina  Teknik Elektro     92         6
2  Charlie    Teknik Sipil     78         4
3     Dewi    Teknik Mesin     90         6
4      Eko  Teknik Elektro     88         4

In [51]:
# ── Properti dasar DataFrame ──

print(f"Shape (baris, kolom) : {df.shape}")
print(f"Jumlah baris         : {len(df)}")
print(f"Jumlah kolom         : {len(df.columns)}")
print(f"Nama kolom           : {list(df.columns)}")
print(f"Tipe data per kolom  :")
print(df.dtypes)

Shape (baris, kolom) : (5, 4)
Jumlah baris         : 5
Jumlah kolom         : 4
Nama kolom           : ['nama', 'jurusan', 'nilai', 'semester']
Tipe data per kolom  :
nama          str
jurusan       str
nilai       int64
semester    int64
dtype: object

---
## 2️⃣ Membaca Data dari File

Pandas dapat membaca berbagai format file. Kita akan membuat contoh data CSV terlebih dahulu.

In [52]:
# ── Membuat contoh file CSV ──

contoh_csv = """nama,usia,kota,gaji
Budi,28,Jakarta,8500000
Rina,25,Bandung,7200000
Charlie,32,Surabaya,9500000
Dewi,27,Jakarta,8000000
Eko,30,Bandung,7800000
Fajar,35,Surabaya,11000000
Gita,29,Jakarta,9000000
Hadi,31,Bandung,8200000
Intan,26,Surabaya,7500000
Joko,33,Jakarta,10500000
"""

with open("data/data_karyawan.csv", "w") as f:
    f.write(contoh_csv)

print("File data_karyawan.csv berhasil dibuat ✓")

File data_karyawan.csv berhasil dibuat ✓

In [53]:
# ── Membaca CSV ──

df_karyawan = pd.read_csv("data/data_karyawan.csv")
print("Data karyawan dari CSV:")
df_karyawan

Data karyawan dari CSV:

      nama  usia      kota      gaji
0     Budi    28   Jakarta   8500000
1     Rina    25   Bandung   7200000
2  Charlie    32  Surabaya   9500000
3     Dewi    27   Jakarta   8000000
4      Eko    30   Bandung   7800000
5    Fajar    35  Surabaya  11000000
6     Gita    29   Jakarta   9000000
7     Hadi    31   Bandung   8200000
8    Intan    26  Surabaya   7500000
9     Joko    33   Jakarta  10500000

In [54]:
# ── Opsi tambahan saat membaca CSV ──

# Gunakan kolom 'nama' sebagai index
df_index = pd.read_csv("data/data_karyawan.csv", index_col="nama")
print("DataFrame dengan index = nama:")
df_index

DataFrame dengan index = nama:

         usia      kota      gaji
nama
Budi       28   Jakarta   8500000
Rina       25   Bandung   7200000
Charlie    32  Surabaya   9500000
Dewi       27   Jakarta   8000000
Eko        30   Bandung   7800000
Fajar      35  Surabaya  11000000
Gita       29   Jakarta   9000000
Hadi       31   Bandung   8200000
Intan      26  Surabaya   7500000
Joko       33   Jakarta  10500000

---
## 3️⃣ Eksplorasi Data

Setelah data dimuat, langkah pertama adalah **memahami strukturnya**.

In [55]:
# ── Melihat data: head() & tail() ──

print("── 5 baris pertama (head) ──")
print(df_karyawan.head())

print("\n── 3 baris pertama (head(3)) ──")
print(df_karyawan.head(3))

print("\n── 3 baris terakhir (tail(3)) ──")
print(df_karyawan.tail(3))

── 5 baris pertama (head) ──
      nama  usia      kota     gaji
0     Budi    28   Jakarta  8500000
1     Rina    25   Bandung  7200000
2  Charlie    32  Surabaya  9500000
3     Dewi    27   Jakarta  8000000
4      Eko    30   Bandung  7800000

── 3 baris pertama (head(3)) ──
      nama  usia      kota     gaji
0     Budi    28   Jakarta  8500000
1     Rina    25   Bandung  7200000
2  Charlie    32  Surabaya  9500000

── 3 baris terakhir (tail(3)) ──
    nama  usia      kota      gaji
7   Hadi    31   Bandung   8200000
8  Intan    26  Surabaya   7500000
9   Joko    33   Jakarta  10500000

In [56]:
# ── Info & Statistik Deskriptif ──

print("── info() — tipe data & non-null count ──")
print(df_karyawan.info())

print("\n── describe() — statistik numerik ──")
print(df_karyawan.describe())

── info() — tipe data & non-null count ──
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nama    10 non-null     str
 1   usia    10 non-null     int64
 2   kota    10 non-null     str
 3   gaji    10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 452.0 bytes
None

── describe() — statistik numerik ──
            usia          gaji
count  10.000000  1.000000e+01
mean   29.600000  8.720000e+06
std     3.204164  1.270870e+06
min    25.000000  7.200000e+06
25%    27.250000  7.850000e+06
50%    29.500000  8.350000e+06
75%    31.750000  9.375000e+06
max    35.000000  1.100000e+07

In [57]:
# ── Unique, value_counts, dan ringkasan kategorikal ──

print("Kota yang ada:", df_karyawan["kota"].unique())
print("Jumlah tiap kota:")
print(df_karyawan["kota"].value_counts())
print()

print("Statistik kolom kategorikal:")
print(df_karyawan.describe(include=["object"]))

Kota yang ada: <StringArray>
['Jakarta', 'Bandung', 'Surabaya']
Length: 3, dtype: str
Jumlah tiap kota:
kota
Jakarta     4
Bandung     3
Surabaya    3
Name: count, dtype: int64

Statistik kolom kategorikal:
        nama     kota
count     10       10
unique    10        3
top     Budi  Jakarta
freq       1        4

/var/folders/6s/4n20n38x5y571387phy8c5lc0000gn/T/ipykernel_28106/3492084347.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df_karyawan.describe(include=["object"]))

---
## 4️⃣ Seleksi & Filtering

Memilih baris/kolom tertentu dari DataFrame.

In [58]:
# ── Memilih kolom ──

# Satu kolom → Series
print("── Kolom 'nama' (Series) ──")
print(df_karyawan["nama"])

print("\n── Beberapa kolom (DataFrame) ──")
print(df_karyawan[["nama", "gaji"]])

── Kolom 'nama' (Series) ──
0       Budi
1       Rina
2    Charlie
3       Dewi
4        Eko
5      Fajar
6       Gita
7       Hadi
8      Intan
9       Joko
Name: nama, dtype: str

── Beberapa kolom (DataFrame) ──
      nama      gaji
0     Budi   8500000
1     Rina   7200000
2  Charlie   9500000
3     Dewi   8000000
4      Eko   7800000
5    Fajar  11000000
6     Gita   9000000
7     Hadi   8200000
8    Intan   7500000
9     Joko  10500000

In [59]:
# ── Seleksi baris: iloc (index) vs loc (label) ──

print("── iloc[0] — baris pertama (index 0) ──")
print(df_karyawan.iloc[0])

print("\n── iloc[1:4] — baris 1 s/d 3 ──")
print(df_karyawan.iloc[1:4])

print("\n── iloc[0, 2] — baris 0, kolom 2 ──")
print(df_karyawan.iloc[0, 2])

print("\n── iloc[:, 0:3] — semua baris, kolom 0-2 ──")
print(df_karyawan.iloc[:, 0:3])

── iloc[0] — baris pertama (index 0) ──
nama       Budi
usia         28
kota    Jakarta
gaji    8500000
Name: 0, dtype: object

── iloc[1:4] — baris 1 s/d 3 ──
      nama  usia      kota     gaji
1     Rina    25   Bandung  7200000
2  Charlie    32  Surabaya  9500000
3     Dewi    27   Jakarta  8000000

── iloc[0, 2] — baris 0, kolom 2 ──
Jakarta

── iloc[:, 0:3] — semua baris, kolom 0-2 ──
      nama  usia      kota
0     Budi    28   Jakarta
1     Rina    25   Bandung
2  Charlie    32  Surabaya
3     Dewi    27   Jakarta
4      Eko    30   Bandung
5    Fajar    35  Surabaya
6     Gita    29   Jakarta
7     Hadi    31   Bandung
8    Intan    26  Surabaya
9     Joko    33   Jakarta

In [60]:
# ── Boolean indexing (filtering dengan kondisi) ──

# Karyawan dengan gaji > 8 juta
print("── Gaji > 8.000.000 ──")
print(df_karyawan[df_karyawan["gaji"] > 8000000])

print("\n── Karyawan di Jakarta ──")
print(df_karyawan[df_karyawan["kota"] == "Jakarta"])

print("\n── Karyawan di Jakarta dengan gaji > 8jt ──")
kondisi = (df_karyawan["kota"] == "Jakarta") & (df_karyawan["gaji"] > 8000000)
print(df_karyawan[kondisi])

print("\n── Karyawan di Bandung atau Surabaya ──")
print(df_karyawan[df_karyawan["kota"].isin(["Bandung", "Surabaya"])])

── Gaji > 8.000.000 ──
      nama  usia      kota      gaji
0     Budi    28   Jakarta   8500000
2  Charlie    32  Surabaya   9500000
5    Fajar    35  Surabaya  11000000
6     Gita    29   Jakarta   9000000
7     Hadi    31   Bandung   8200000
9     Joko    33   Jakarta  10500000

── Karyawan di Jakarta ──
   nama  usia     kota      gaji
0  Budi    28  Jakarta   8500000
3  Dewi    27  Jakarta   8000000
6  Gita    29  Jakarta   9000000
9  Joko    33  Jakarta  10500000

── Karyawan di Jakarta dengan gaji > 8jt ──
   nama  usia     kota      gaji
0  Budi    28  Jakarta   8500000
6  Gita    29  Jakarta   9000000
9  Joko    33  Jakarta  10500000

── Karyawan di Bandung atau Surabaya ──
      nama  usia      kota      gaji
1     Rina    25   Bandung   7200000
2  Charlie    32  Surabaya   9500000
4      Eko    30   Bandung   7800000
5    Fajar    35  Surabaya  11000000
7     Hadi    31   Bandung   8200000
8    Intan    26  Surabaya   7500000

In [61]:
# ── Method query() — alternatif yang lebih bersih ──

print("── query: gaji > 8jt ──")
print(df_karyawan.query("gaji > 8000000"))

print("\n── query: Jakarta dan gaji > 8jt ──")
print(df_karyawan.query("kota == 'Jakarta' and gaji > 8000000"))

── query: gaji > 8jt ──
      nama  usia      kota      gaji
0     Budi    28   Jakarta   8500000
2  Charlie    32  Surabaya   9500000
5    Fajar    35  Surabaya  11000000
6     Gita    29   Jakarta   9000000
7     Hadi    31   Bandung   8200000
9     Joko    33   Jakarta  10500000

── query: Jakarta dan gaji > 8jt ──
   nama  usia     kota      gaji
0  Budi    28  Jakarta   8500000
6  Gita    29  Jakarta   9000000
9  Joko    33  Jakarta  10500000

---
## 📚 Rangkuman

| Konsep | Method / Cara | Contoh |
|--------|--------------|--------|
| **Membaca CSV** | `pd.read_csv()` | `df = pd.read_csv("file.csv")` |
| **Melihat data** | `head()`, `tail()`, `info()`, `describe()` | `df.head(10)` |
| **Seleksi kolom** | `df["kolom"]`, `df[["a","b"]]` | `df["nama"]` |
| **Seleksi baris** | `iloc[]`, `loc[]`, `query()` | `df.iloc[0:5]` |
| **Filtering** | Boolean indexing | `df[df["gaji"] > 10000]` |